version: "2.0"

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.2.0.0/16

services:
  php:
    build: .
    ports:
     - "8082:80"
    volumes:
     - ./www:/var/www/html
    links:
     - mysql:mysql
    networks:
      mynet:
          ipv4_address: 10.2.0.2
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - ./var/lib/mysql:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=phprs
     - MYSQL_DATABASE=phprs
    networks:
      mynet:
          ipv4_address: 10.2.0.3





